<a href="https://colab.research.google.com/github/enigmamind/erfa/blob/main/Copy_of_Updated_Code_for_Uniswap_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CHECK FOR EMPTY ROW and Empty values

In [ ]:
import pandas as pd

# Load your data
df = pd.read_csv('UNISWAP-DATA.csv', parse_dates=['Date'])

# Check for rows that contain '[]'
brackets_rows = df[df.apply(lambda row: row.astype(str).str.contains(r'\[\]').any(), axis=1)]

# Check for completely empty rows (rows where all values are NaN)
empty_rows = df[df.isnull().all(axis=1)]

# Print details about rows containing '[]'
if not brackets_rows.empty:
    print("Rows containing '[]':")
    print(brackets_rows)
    print(f"Total rows containing '[]': {len(brackets_rows)}")
else:
    print("No rows containing '[]' found.")

# Print details about completely empty rows
if not empty_rows.empty:
    print("\nCompletely Empty Rows:")
    print(empty_rows)
    print(f"Total empty rows: {len(empty_rows)}")
else:
    print("No completely empty rows found.")

No rows containing '[]' found.
No completely empty rows found.

THIS GIVE ALL DATA WITH ZERO ROWS

In [ ]:
import pandas as pd
import json
import re

def extract_weth_usdt_and_ratio(token_transferred):
    if not isinstance(token_transferred, str):
        return pd.Series({'WETH_Amount': 0, 'USDT_Amount': 0, 'Ratio': 0})

    try:
        data = json.loads(token_transferred)[0]['Token_Transferred']
        weth_match = re.search(r'For([\d.]+)\(\$[\d.]+\)Wrapped Ethe... \(WETH\)', data)
        usdt_match = re.search(r'For([\d.]+)\(\$[\d.]+\)Tether USD \(USDT\)', data)

        weth_amount = float(weth_match.group(1)) if weth_match else 0
        usdt_amount = float(usdt_match.group(1)) if usdt_match else 0

        # Calculate ratio (USDT per WETH)
        ratio = abs(usdt_amount / weth_amount) if weth_amount != 0 else 0

        return pd.Series({'WETH_Amount': weth_amount, 'USDT_Amount': usdt_amount, 'Ratio': ratio})
    except (json.JSONDecodeError, KeyError, IndexError, AttributeError):
        return pd.Series({'WETH_Amount': 0, 'USDT_Amount': 0, 'Ratio': 0})

# Load your data
df = pd.read_csv('test-data.csv', parse_dates=['Date'])

# Apply the extraction and ratio calculation function
df[['WETH_Amount', 'USDT_Amount', 'Ratio']] = df['Token_Transferred'].apply(extract_weth_usdt_and_ratio)

# Display the result
print(df[['Transanction_Hash', 'Date', 'WETH_Amount', 'USDT_Amount', 'Ratio']])

# Save the updated dataframe to a new CSV file
df.to_csv('updated_swap_data_with_ratio.csv', index=False)

                                    Transanction_Hash                Date  \
0   0x4a20d1a3df26871c550cfb45afc662021af93429544d... 2023-12-06 06:20:00
1   0x085a9cdad1b03359a3fcf2c872a22c40c60bd7726b70... 2023-12-06 06:25:00
2   0xb78b64bb983649a1be4553a6ce1657d1ae5271c9a5cf... 2023-12-06 06:26:00
3   0xc1dbc1c19e28e1264b9d0227074e5aa83f4b2471e666... 2023-12-06 06:27:00
4   0x3bb3a3c4de0407ff3a6e2b9b312e2c2c1510f27987ed... 2023-12-06 06:30:00
5   0x0ea3740e04975758c533f5dfa79c1e2a255002911e0b... 2023-12-06 06:31:00
6   0x9e89945c25702f82ec7f3c88934fc1bd17479fee7c5d... 2023-12-06 06:33:00
7   0x1a0c07870b90f1a8d7037d563d9291db91cfda6303fe... 2023-12-06 06:37:00
8   0x8a5817bbfa962380653bc6f5bdb035bdd2b3381bddb5... 2023-12-06 06:38:00
9   0x54d27437c5dd342554d0b78f129dd950a2f88c76af51... 2023-12-06 06:42:00
10  0xd6192b6090fcf497fa030f245c9aa2debb2a981d709b... 2023-12-06 06:44:00
11                                                NaN                 NaT

    WETH_Amount  USDT_Amount        Ratio
0      0.066430   150.225000  2261.406687
1      0.129089   293.235892  2271.578182
2      0.000000     0.000000     0.000000
3      0.000000     0.000000     0.000000
4      0.000000     6.795183     0.000000
5      0.035000    79.305262  2265.864629
6      0.008859    20.030000  2260.988736
7      0.000000     0.000000     0.000000
8      0.000000     0.000000     0.000000
9      0.000000    15.319760     0.000000
10     0.030458    68.963290  2264.240005
11     0.000000     0.000000     0.000000

THIS CODE REMOVE ROWS WITH ZERO AND PRINT ALL DATA

In [ ]:
import pandas as pd
import json
import re

def extract_weth_usdt_and_ratio(token_transferred):
    if not isinstance(token_transferred, str):
        return pd.Series({'WETH_Amount': 0, 'USDT_Amount': 0, 'Ratio': 0})

    try:
        data = json.loads(token_transferred)[0]['Token_Transferred']
        weth_match = re.search(r'For([\d.]+)\(\$[\d.]+\)Wrapped Ethe... \(WETH\)', data)
        usdt_match = re.search(r'For([\d.]+)\(\$[\d.]+\)Tether USD \(USDT\)', data)

        weth_amount = float(weth_match.group(1)) if weth_match else 0
        usdt_amount = float(usdt_match.group(1)) if usdt_match else 0

        # Calculate ratio (USDT per WETH)
        ratio = abs(usdt_amount / weth_amount) if weth_amount != 0 else 0

        return pd.Series({'WETH_Amount': weth_amount, 'USDT_Amount': usdt_amount, 'Ratio': ratio})
    except (json.JSONDecodeError, KeyError, IndexError, AttributeError):
        return pd.Series({'WETH_Amount': 0, 'USDT_Amount': 0, 'Ratio': 0})

# Load your data
df = pd.read_csv('UNISWAP-DATA.csv', parse_dates=['Date'])

# Apply the extraction and ratio calculation function
df[['WETH_Amount', 'USDT_Amount', 'Ratio']] = df['Token_Transferred'].apply(extract_weth_usdt_and_ratio)

# Remove rows where WETH_Amount, USDT_Amount, and Ratio are all 0
df = df[(df['WETH_Amount'] != 0) | (df['USDT_Amount'] != 0) | (df['Ratio'] != 0)]

# Display the result
print(df[['Transanction_Hash', 'Date', 'WETH_Amount', 'USDT_Amount', 'Ratio']])

# Save the updated dataframe to a new CSV file
df.to_csv('updated_swap_data_with_ratio.csv', index=False)

                                       Transanction_Hash                Date  \
0      0x4a20d1a3df26871c550cfb45afc662021af93429544d... 2023-12-06 06:20:00
1      0x085a9cdad1b03359a3fcf2c872a22c40c60bd7726b70... 2023-12-06 06:25:00
4      0x3bb3a3c4de0407ff3a6e2b9b312e2c2c1510f27987ed... 2023-12-06 06:30:00
5      0x0ea3740e04975758c533f5dfa79c1e2a255002911e0b... 2023-12-06 06:31:00
6      0x9e89945c25702f82ec7f3c88934fc1bd17479fee7c5d... 2023-12-06 06:33:00
...                                                  ...                 ...
47757  0xbf3251e8be075d19097631559a9a85f51f027397d80f... 2024-01-31 23:56:00
47758  0xb15c82514a35e4407464ed41d050945c2061de601acc... 2024-01-31 23:56:00
47759  0x6ba59e05ed326c00c27781b82846b9c24ed1623692cc... 2024-01-31 23:57:00
47760  0xc26d7fa8e6671fd379cea571954addcb8c01a04512a5... 2024-01-31 23:57:00
47761  0xa96d22c23c1694ec366e0038d344609d929e426fb655... 2024-01-31 23:58:00

       WETH_Amount  USDT_Amount        Ratio
0         0.066430   150.225000  2261.406687
1         0.129089   293.235892  2271.578182
4         0.000000     6.795183     0.000000
5         0.035000    79.305262  2265.864629
6         0.008859    20.030000  2260.988736
...            ...          ...          ...
47757     0.025000    57.060884  2282.435360
47758     0.000000    68.452273     0.000000
47759     0.000000   200.224358     0.000000
47760     0.069705   159.013298  2281.236108
47761     0.000000   958.112052     0.000000

[36805 rows x 5 columns]

THIS CODE REMOVE THE ROWS WITH ZERO BECAUSE OF AVERAGE RATION

*   DOWNSIDE IS IT WON'T OUT TIME STAMP IN 5 MIN INTERVAL
*   List item

In [ ]:
import pandas as pd
import json
import re
from datetime import datetime, timedelta

def extract_weth_usdt_and_ratio(token_transferred):
    if isinstance(token_transferred, str):
        try:
            data = json.loads(token_transferred)[0]['Token_Transferred']
            weth_match = re.search(r'For([\d.]+)\(\$[\d.]+\)Wrapped Ethe... \(WETH\)', data)
            usdt_match = re.search(r'For([\d.]+)\(\$[\d.]+\)Tether USD \(USDT\)', data)

            weth_amount = float(weth_match.group(1)) if weth_match else 0
            usdt_amount = float(usdt_match.group(1)) if usdt_match else 0

            ratio = abs(usdt_amount / weth_amount) if weth_amount != 0 else 0

            return pd.Series({'WETH_Amount': weth_amount, 'USDT_Amount': usdt_amount, 'Ratio': ratio})
        except (json.JSONDecodeError, IndexError):
            return pd.Series({'WETH_Amount': 0, 'USDT_Amount': 0, 'Ratio': 0})
    else:
        return pd.Series({'WETH_Amount': 0, 'USDT_Amount': 0, 'Ratio': 0})

def round_to_5min(dt):
    if pd.isnull(dt):
        return pd.NaT
    return dt - timedelta(minutes=dt.minute % 5, seconds=dt.second, microseconds=dt.microsecond)

# Load your data
df = pd.read_csv('test-data.csv', parse_dates=['Date'])

# Apply the extraction and ratio calculation function
df[['WETH_Amount', 'USDT_Amount', 'Ratio']] = df['Token_Transferred'].apply(extract_weth_usdt_and_ratio)

# Remove rows where WETH_Amount, USDT_Amount, and Ratio are all zero
df = df[(df['WETH_Amount'] != 0) | (df['USDT_Amount'] != 0) | (df['Ratio'] != 0)]

# Create 5-minute bins
df['Five_Minute_Bin'] = df['Date'].apply(round_to_5min)

# Remove rows with NaT values in Five_Minute_Bin
df = df.dropna(subset=['Five_Minute_Bin'])

# Group by 5-minute bins and calculate aggregates
grouped = df.groupby('Five_Minute_Bin').agg({
    'WETH_Amount': 'sum',
    'USDT_Amount': 'sum',
    'Ratio': 'mean',
    'Transanction_Hash': 'count'
}).reset_index()

# Rename columns for clarity
grouped.columns = ['Five_Minute_Bin', 'Total_WETH', 'Total_USDT', 'Average_Ratio', 'Number_Tx']

# Display the result
print(grouped)

# Save the aggregated data to a new CSV file
grouped.to_csv('aggregated_swap_data_5min.csv', index=False)

      Five_Minute_Bin  Total_WETH  Total_USDT  Average_Ratio  Number_Tx
0 2023-12-06 06:20:00    0.066430  150.225000    2261.406687          1
1 2023-12-06 06:25:00    0.129089  293.235892    2271.578182          1
2 2023-12-06 06:30:00    0.043859  106.130445    1508.951122          3
3 2023-12-06 06:40:00    0.030458   84.283050    1132.120003          2

CALCULATE AVG RATIO AND OVERALL RATIO

In [ ]:
import pandas as pd
import json
import re
from datetime import datetime, timedelta

def extract_weth_usdt_and_ratio(token_transferred):
    if isinstance(token_transferred, str):
        try:
            data = json.loads(token_transferred)[0]['Token_Transferred']
            weth_match = re.search(r'For([\d.]+)\(\$[\d.]+\)Wrapped Ethe... \(WETH\)', data)
            usdt_match = re.search(r'For([\d.]+)\(\$[\d.]+\)Tether USD \(USDT\)', data)

            weth_amount = float(weth_match.group(1)) if weth_match else 0
            usdt_amount = float(usdt_match.group(1)) if usdt_match else 0

            ratio = usdt_amount / weth_amount if weth_amount != 0 else 0

            return pd.Series({'WETH_Amount': weth_amount, 'USDT_Amount': usdt_amount, 'Ratio': ratio})
        except (json.JSONDecodeError, IndexError):
            return pd.Series({'WETH_Amount': 0, 'USDT_Amount': 0, 'Ratio': 0})
    else:
        return pd.Series({'WETH_Amount': 0, 'USDT_Amount': 0, 'Ratio': 0})

def round_to_5min(dt):
    if pd.isnull(dt):
        return pd.NaT
    return dt - timedelta(minutes=dt.minute % 5, seconds=dt.second, microseconds=dt.microsecond)

# Load your data
df = pd.read_csv('UNISWAP-DATA.csv', parse_dates=['Date'])

# Apply the extraction and ratio calculation function
df[['WETH_Amount', 'USDT_Amount', 'Ratio']] = df['Token_Transferred'].apply(extract_weth_usdt_and_ratio)

# Create 5-minute bins
df['Five_Minute_Bin'] = df['Date'].apply(round_to_5min)

# Remove rows with NaT values in Five_Minute_Bin
df = df.dropna(subset=['Five_Minute_Bin'])

# Group by 5-minute bins and calculate aggregates
grouped = df.groupby('Five_Minute_Bin').agg({
    'WETH_Amount': 'sum',
    'USDT_Amount': 'sum',
    'Ratio': lambda x: sum(x[x != 0]) / len(x[x != 0]) if len(x[x != 0]) > 0 else 0,  # Average of non-zero ratios
    'Transanction_Hash': 'count'
}).reset_index()

# Rename columns for clarity
grouped.columns = ['Five_Minute_Bin', 'Total_WETH', 'Total_USDT', 'Average_Ratio', 'Number_Tx']

# Calculate the overall ratio for each bin
grouped['Overall_Ratio'] = grouped['Total_USDT'] / grouped['Total_WETH']

# Display the result
print(grouped)

# Save the aggregated data to a new CSV file
grouped.to_csv('aggregated_swap_data_5min.csv', index=False)

          Five_Minute_Bin  Total_WETH   Total_USDT  Average_Ratio  Number_Tx  \
0     2023-12-06 06:20:00    0.066430   150.225000    2261.406687          1
1     2023-12-06 06:25:00    0.129089   293.235892    2271.578182          3
2     2023-12-06 06:30:00    0.043859   106.130445    2263.426683          3
3     2023-12-06 06:35:00    0.000000     0.000000       0.000000          2
4     2023-12-06 06:40:00    0.030458    84.283050    2264.240005          3
...                   ...         ...          ...            ...        ...
14767 2024-01-31 23:35:00    0.296523   674.436339    2274.667422          4
14768 2024-01-31 23:40:00    0.000000     5.250000       0.000000          3
14769 2024-01-31 23:45:00    0.327905   758.026229    2286.210643          4
14770 2024-01-31 23:50:00    0.225455   586.010447    2280.586242          6
14771 2024-01-31 23:55:00    0.094705  1478.112865    2281.835734          8

       Overall_Ratio
0       2.261407e+03
1       2.271578e+03
2       2.419812e+03
3                NaN
4       2.767227e+03
...              ...
14767   2.274485e+03
14768            inf
14769   2.311727e+03
14770   2.599237e+03
14771   1.560757e+04

[14772 rows x 6 columns]

In [ ]:
df4 = pd.read_csv('aggregated_swap_data_5min.csv')
df4.tail()

,Five_Minute_Bin,Total_WETH,Total_USDT,Average_Ratio,Number_Tx,Overall_Ratio
14767,2024-01-31 23:35:00,0.296523,674.436339,2274.667422,4,2.274485e+03
14768,2024-01-31 23:40:00,0.000000,5.250000,0.000000,3,inf
14769,2024-01-31 23:45:00,0.327905,758.026229,2286.210643,4,2.311727e+03
14770,2024-01-31 23:50:00,0.225455,586.010447,2280.586242,6,2.599237e+03
14771,2024-01-31 23:55:00,0.094705,1478.112865,2281.835734,8,1.560757e+04